- docs/team/justinnje.md
> Add PPP skeletal

- docs/DeveloperGuide.md
Added User Stories. More user stories will be added in the future
> Update Development Guide

- docs/DeveloperGuide.md
Insertion of some use cases, will insert the remaining when I receive them
> Insert some of the use cases into DG

- README.md
- docs/_config.yml
Update CI banners in README.md and _config.yml
> Update CI banners in README.md and _config.yml

- docs/AboutUs.md
* added chanyijuan.png to /images
* removed portfolio link
* updated github profile link
> Updated AboutUs.md

- docs/AboutUs.md
Remove "Johnny Doe" and changed img src from ro4k9.jpg to r04k9.png
> Remove dummy values in AboutUs.md and fix img url

- src/main/java/seedu/address/model/applicant/Applicant.java
- src/main/java/seedu/address/model/applicant/Id.java
- src/main/java/seedu/address/model/applicant/Nric.java
- src/test/java/seedu/address/logic/commands/applicant/AddApplicantTest.java
- src/test/java/seedu/address/model/applicant/IdTest.java
- src/test/java/seedu/address/model/applicant/NricTest.java
- src/test/java/seedu/address/testutil/TypicalApplicants.java
- Add Id generation in Applicant class and ensure always positive hash
- Add Validation regex for Nric 
- Add test classes for Id and Nric
> Add Id generation in Applicant class

- src/main/java/seedu/address/model/applicant/Applicant.java
- src/main/java/seedu/address/model/applicant/InterviewDate.java
- src/main/java/seedu/address/model/applicant/JobId.java
- src/main/java/seedu/address/model/applicant/Qualification.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
> Fix Data file read error

- src/main/java/seedu/address/logic/commands/applicant/EditApplicant.java
Allows the editapplicant to edit job id
> Add JobId to editapplicant

- src/main/java/seedu/address/model/job/JobStatus.java
- src/test/java/seedu/address/model/job/JobStatusTest.java
* added JobStatus field to job package
* added JobStatusTest cases
> Add JobStatus

- src/main/java/seedu/address/model/job/JobStatus.java
- src/test/java/seedu/address/model/job/JobStatusTest.java
* jobStatus field changed from boolean to string
* add isValid method to validate user input
> Change JobStatus constructor to accept String

- src/main/java/seedu/address/logic/parser/CliSyntax.java
* added "js/", "pos/" prefixes to CliSyntax
NOTE: pushed from new branch to avoid merge conflicts
> Add JobStatus, Position prefix

- src/main/java/seedu/address/model/job/Position.java
- src/test/java/seedu/address/model/job/PositionTest.java
* added Position class to job package
* added PositionTest test cases
> Add Position

- src/main/java/seedu/address/logic/commands/applicant/MarkApplicant.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
A change is made to convert status values (pending, rejected, accepted, interviewed) into numeric status value (0, 1, 2, 3) before applying isValidStatus since isValidStatus parse the argument into integers and see if a parsed integer is in a correct range.
> Fix the error in ParserUtil#parseApplicantStatus

- src/main/java/seedu/address/logic/commands/applicant/EditApplicant.java
Bug was found, the parser did not read any input if editapplicant
was used with only nric field.
Realized that it was missed out in isAnyFieldEdited() method in
EditApplicant class
> Edit EditApplicant

- build.gradle
- src/main/java/seedu/address/logic/commands/job/ListJob.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/test/java/seedu/address/logic/commands/job/ListJobTest.java
- List all jobs by using command `listjob`
> Implement List all Jobs feature

- src/main/java/seedu/address/logic/commands/job/MarkJob.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/job/MarkJobParser.java
Fix duplicate job exception occurs when using markjob command
> Fix bug in mark job

- src/main/java/seedu/address/model/util/SampleDataUtil.java
Add one more sample job to the default ReCLIne
> Add new Job to sample book

- src/main/java/seedu/address/ui/InfoPanel.java
- src/main/java/seedu/address/ui/StyleUtil.java
- src/main/java/seedu/address/ui/applicant/ApplicantCard.java
- src/main/java/seedu/address/ui/job/JobCard.java
- src/main/resources/view/ApplicantListCard.fxml
- src/main/resources/view/JobListCard.fxml
- src/main/resources/view/MainWindow.fxml
- Edit Applicant Card to display attributes that are being sorted (dateapplied, job id, interview date)
- Edit the Job Card to display attributes that are being sorted (job status)
- Fix an issue with resizing the window (now the list panel expands vertically)
> Edit Applicant and Job Card

- src/main/java/seedu/address/logic/commands/applicant/AddApplicant.java
- src/main/java/seedu/address/logic/parser/applicant/AddApplicantParser.java
- src/main/java/seedu/address/model/applicant/DateApplied.java
- src/main/java/seedu/address/model/applicant/InterviewDate.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/applicant/AddApplicantParserTest.java
- src/test/java/seedu/address/model/applicant/DateAppliedTest.java
- src/test/java/seedu/address/model/applicant/InterviewDateTest.java
Invalid dates E.g 2022-02-30 are rejected. Applied this change for both date applied and interviewdate, and created test cases for the respective tests.
Also changed Add Applicant such that the non compulsory fields will throw an error when used in AddApplicant
> Change validation of Dateapplied and interviewDate

- README.md
- docs/UserGuide.md
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/applicant/Qualification.java
- src/main/java/seedu/address/model/job/CompanyName.java
- src/main/java/seedu/address/model/job/JobTitle.java
Removed test comment in Readme
Changed the Version number
Edited the message throw by classes to explain what "alphanumberic
characters" means
Edit UG comments from PE
> Edit Documentations

- src/main/java/seedu/address/logic/commands/applicant/SortApplicant.java
* include valid inputs and example command usage to error message
> SortApplicant error message

- src/main/java/seedu/address/model/job/Salary.java
- src/test/java/seedu/address/model/job/SalaryTest.java
Change Salary's regex to allow only maximum of 9 digits and disallow salary starting with 0
> Change Salary's regex to allow only maximum of 9 digits and disallow

- src/main/java/seedu/address/ui/job/JobCard.java
- Change sub-header for JobID in Ui from # to 'Job ID:' to avoid confusion with index
> Change sub-header for JobID in Ui

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/applicant/AddApplicant.java
- src/main/java/seedu/address/logic/commands/applicant/MarkApplicant.java
- src/main/java/seedu/address/logic/commands/applicant/TabApplicant.java
- src/main/java/seedu/address/logic/commands/job/TabJob.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/applicant/MarkApplicantParser.java
- src/main/java/seedu/address/model/applicant/ApplicantStatus.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/applicant/TabApplicantTest.java
- src/test/java/seedu/address/logic/commands/job/TabJobTest.java
- src/test/java/seedu/address/logic/commands/person/ClearCommandTest.java
- src/test/java/seedu/address/logic/parser/applicant/MarkApplicantParserTest.java
- Add test case for TabApplicant and TabJob
- Edit test case for Clear Command
- Edit test case for CommandResult
- Edit CommandResult class equal method and constructor to reflect newly added argument resetPanel
- Add test case for MarkApplicantParser
- Edit message constraint  for ApplicantStatus class
- Edit ParserUtil#ParsePredicate to make use of unused method ParserUtil#ParseId
> Add and edit test case

- docs/UserGuide.md
* changed 'to leave out optional fields' remark to 'all fields are mandatory'
> UG: Updated markapplicant tip

- docs/UserGuide.md
* formatted valid attribute to <code> </code> in command descriptor
> UG: SortApplicant command description

- src/main/java/seedu/address/logic/commands/job/EditJob.java
- src/main/java/seedu/address/model/applicant/Applicant.java
Fix bug qhere qualification does not register
fix message for editjob
> edit editapplicant and editjob

- src/main/java/seedu/address/logic/commands/applicant/MarkApplicant.java
* displays updated application status in message box upon markapplicant command success
> Fix error message for MarkApplicant

- docs/DeveloperGuide.md
* added instructions for manual testing to DG
> DG: MarkApplicant, MarkJob, SortApplicant

- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/job/MarkJobParserTest.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
* added JUnit tests for success, throws, failure for MarkJobParser (MarkJobParseTest)
> Add MarkJobParserTest
